# Yes this sucks. We need to pull all the images once every six month
# so we dont loose them to the new docker rentention period
# We wont migrate this application to github packages but might use it
# for future images

name: Docker Pull Periodically
on:
  workflow_dispatch:
  # https://crontab.guru/#0_8_1_*_*
  schedule:
    - cron: "0 12 1 * *"
jobs:
  pull:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Pull them
        run: |
          images=(
            "technologiestiftung/giessdenkiez-de-dwd-harvester:v1.1.4"
            "technologiestiftung/dwd-radolan-tree-harvester:latest"
            "technologiestiftung/dwd-radolan-tree-harvester:1.1.3"
          )
          for i in "${images[@]}"; do
            docker pull "$i"
          done
