name: harvester (test mode)

on:
  push:
    branches:
      - master
      - staging
      - port-to-md
  pull_request:
    branches:
      - master
      - staging
      - port-to-md
  workflow_dispatch:

env:
  PG_SERVER: localhost
  PG_PORT: "54322"
  PG_USER: postgres
  PG_PASS: postgres
  PG_DB: postgres
  SUPABASE_PROJECT_ID: ${{ vars.SUPABASE_PROJECT_ID_TEST }}
  SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN_TEST }}
  SUPABASE_BUCKET_NAME: ${{ vars.SUPABASE_BUCKET_NAME_TEST }}
  OUTPUT: "True"
  MAPBOXUSERNAME: "123"
  MAPBOXTOKEN: "456"
  MAPBOXTILESET: "xyz"
  MAPBOXLAYERNAME: "abc"
  LOGGING: INFO

jobs:
  test-harvest:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    steps:
      - name: Get the source
        uses: actions/checkout@v3
      - name: Get the source for the api master-magdeburg
        uses: actions/checkout@v3
        if: github.event.pull_request.base.ref == 'port-to-md' || github.ref == 'refs/heads/port-to-md'
        with:
          repository: code-for-magdeburg/magdeburggiesst-postgres-api
          path: api
          ref: master-magdeburg
      - name: Get the source for the api staging
        uses: actions/checkout@v3
        if: github.event.pull_request.base.ref == 'staging' || github.ref == 'refs/heads/staging'
        with:
          repository: code-for-magdeburg/magdeburggiesst-postgres-api
          path: api
          ref: staging
      - name: Get the source for the api master
        uses: actions/checkout@v3
        if: github.event.pull_request.base.ref == 'master' || github.ref == 'refs/heads/master'
        with:
          repository: code-for-magdeburg/magdeburggiesst-postgres-api
          path: api
      - uses: supabase/setup-cli@v1
        with:
          version: 1.33.0
      - name: build the harvester
        run: cd harvester && docker build --tag code-for-magdeburg/magdeburggiesst-dwd-harvester:test .
      - name: Start the api
        run: cd api && supabase start && cd ..
      - name: run the harvester
        run: >
          docker run --env PG_SERVER='0.0.0.0' \
                     --env PG_DB \
                     --env PG_PORT \
                     --env PG_USER \
                     --env PG_PASS \
                     --env SUPABASE_PROJECT_ID \
                     --env SUPABASE_ACCESS_TOKEN \
                     --env SUPABASE_BUCKET_NAME \
                     --env MAPBOXTOKEN \
                     --env MAPBOXUSERNAME \
                     --env LOGGING \
                     --env OUTPUT \
                     --network host \
                     code-for-magdeburg/magdeburggiesst-dwd-harvester:test
      - name: stop the api
        run: cd api && supabase stop && cd ..
